/* eslint-disable @typescript-eslint/naming-convention */

export const assets = {
    images: {
        'elements/blue.png': require('../assets/images/elements/blue.png').default,
        'elements/green.png': require('../assets/images/elements/green.png').default,
        'elements/orange.png': require('../assets/images/elements/orange.png').default,
        'elements/pink.png': require('../assets/images/elements/pink.png').default,
        'elements/red.png': require('../assets/images/elements/red.png').default,
        'game/algae_1.png': require('../assets/images/game/algae_1.png').default,
        'game/algae_2.png': require('../assets/images/game/algae_2.png').default,
        'game/algae_3.png': require('../assets/images/game/algae_3.png').default,
        'game/big_board.png': require('../assets/images/game/big_board.png').default,
        'game/bkg.jpg': require('../assets/images/game/bkg.jpg').default,
        'game/bomb.png': require('../assets/images/game/bomb.png').default,
        'game/bubble.png': require('../assets/images/game/bubble.png').default,
        'game/hand.png': require('../assets/images/game/hand.png').default,
        'game/key.png': require('../assets/images/game/key.png').default,
        'game/play_btn.png': require('../assets/images/game/play_btn.png').default,
        'game/ship.png': require('../assets/images/game/ship.png').default,
        'game/small_board.png': require('../assets/images/game/small_board.png').default,
        'game/sound_off.png': require('../assets/images/game/sound_off.png').default,
        'game/sound_on.png': require('../assets/images/game/sound_on.png').default,
        'game/sword.png': require('../assets/images/game/sword.png').default,
        'game/wave.png': require('../assets/images/game/wave.png').default,
        'pirate/body.png': require('../assets/images/pirate/body.png').default,
        'pirate/eyelid_bottom.png': require('../assets/images/pirate/eyelid_bottom.png').default,
        'pirate/eyelid_top.png': require('../assets/images/pirate/eyelid_top.png').default,
        'pirate/head.png': require('../assets/images/pirate/head.png').default,
        'pirate/left_hand.png': require('../assets/images/pirate/left_hand.png').default,
        'pirate/mouth_closed.png': require('../assets/images/pirate/mouth_closed.png').default,
        'pirate/mouth_mid.png': require('../assets/images/pirate/mouth_mid.png').default,
        'pirate/mouth_open.png': require('../assets/images/pirate/mouth_open.png').default,
        'pirate/mouth_pleased.png': require('../assets/images/pirate/mouth_pleased.png').default,
        'pirate/mouth_sad.png': require('../assets/images/pirate/mouth_sad.png').default,
        'pirate/mouth_scared.png': require('../assets/images/pirate/mouth_scared.png').default,
        'pirate/pupil.png': require('../assets/images/pirate/pupil.png').default,
        'pirate/right_hand.png': require('../assets/images/pirate/right_hand.png').default,
        'pirate/water_layer.png': require('../assets/images/pirate/water_layer.png').default,
    },
    particles: {},
    sounds: {},
    spines: {},
    atlases: {},
};

export const Images = {
    'elements/blue': 'elements/blue.png',
    'elements/green': 'elements/green.png',
    'elements/orange': 'elements/orange.png',
    'elements/pink': 'elements/pink.png',
    'elements/red': 'elements/red.png',
    'game/algae_1': 'game/algae_1.png',
    'game/algae_2': 'game/algae_2.png',
    'game/algae_3': 'game/algae_3.png',
    'game/big_board': 'game/big_board.png',
    'game/bkg': 'game/bkg.jpg',
    'game/bomb': 'game/bomb.png',
    'game/bubble': 'game/bubble.png',
    'game/hand': 'game/hand.png',
    'game/key': 'game/key.png',
    'game/play_btn': 'game/play_btn.png',
    'game/ship': 'game/ship.png',
    'game/small_board': 'game/small_board.png',
    'game/sound_off': 'game/sound_off.png',
    'game/sound_on': 'game/sound_on.png',
    'game/sword': 'game/sword.png',
    'game/wave': 'game/wave.png',
    'pirate/body': 'pirate/body.png',
    'pirate/eyelid_bottom': 'pirate/eyelid_bottom.png',
    'pirate/eyelid_top': 'pirate/eyelid_top.png',
    'pirate/head': 'pirate/head.png',
    'pirate/left_hand': 'pirate/left_hand.png',
    'pirate/mouth_closed': 'pirate/mouth_closed.png',
    'pirate/mouth_mid': 'pirate/mouth_mid.png',
    'pirate/mouth_open': 'pirate/mouth_open.png',
    'pirate/mouth_pleased': 'pirate/mouth_pleased.png',
    'pirate/mouth_sad': 'pirate/mouth_sad.png',
    'pirate/mouth_scared': 'pirate/mouth_scared.png',
    'pirate/pupil': 'pirate/pupil.png',
    'pirate/right_hand': 'pirate/right_hand.png',
    'pirate/water_layer': 'pirate/water_layer.png',
};

export const Sounds = {};

export const Particles = {};

export const Spines = {};
